services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.2
    container_name: elasticsearch
    restart: always
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      discovery.type: single-node
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - ndsnet

  kibana:
    image: docker.elastic.co/kibana/kibana:7.5.2
    container_name: kibana
    restart: always
    depends_on:
      - elasticsearch
    volumes:
      - ./kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
      SERVER_HOST: "0.0.0.0"
    ports:
      - "5601:5601"
    networks:
      - ndsnet

  logstash:
    image: docker.elastic.co/logstash/logstash:7.5.2
    container_name: logstash
    restart: always
    depends_on:
      - elasticsearch
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline
    networks:
      - ndsnet

  metabase:
    container_name: metabase
    image: metabase/metabase
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./include/data/metabase:/metabase-data
    networks:
      - ndsnet

networks:
  ndsnet:
    external: true